### ISSUE TITLE
SubAdapter notifyItemMoved/notifyItemRemoved

### ISSUE THREAD

**Issue by OakOnEll** [martijnvdwoude/recycler-view-merge-adapter#1]
I am having trouble implementing calls to notifyItemRemoved/notifyItemMoved from within my subadapter methods, because these methods would appear to take the outer mergeAdapter position, while the adapter would have its local position.

There is a method getMergePositionForLocalPosition on RecyclerViewMergeAdapter which looks like it would be helpful, but it is currently a private method.
Would it make sense for the subAdapter class to override the notify methods and perform the subadapterPosition->mergePosition before delegating upwards, or perhaps new methods notifySubItemRemoved,etc.?

**Comment by NammariMarkavip** [comment]
+1

**Comment by xingstarx** [comment]
Afater my test, I call subAdapter.notifyItemRemoved or notifyItemMoved, the Recyclerview  display Normal
