### ISSUE TITLE
Can not update the view added

### ISSUE THREAD

**Issue by sukhvir41** [martijnvdwoude/recycler-view-merge-adapter#3]
i have added a view between two adapters and the view has check boxes . i cane update the values of the view ie the TextView values in the view and how to handle the check box clicks in the view

**Comment by xingstarx** [comment]
could you use 
`CheckBox checkBox = (CheckBox) view.findViewById(R.id.checkbox);`
and set OnCheckedChangeListener for checkBox

**Comment by ronaldwolvers** [comment]
You will probably have to call `notifyItemChanged(int position)` (https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#notifyItemChanged(int)). If you do not call this method, `onBindViewHolder()` is never called on your adapter and the ViewHolder will not be able to update the View it holds.
